<?php

namespace Tests\Unit;

use App\Enums\Marketplace;
use App\Models\Integration;
use App\Services\IntegrationService;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;


class IntegrationUnitTest extends TestCase {

    use DatabaseMigrations ;

    protected function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function an_integration_can_be_add_via_unit() {

        $service = new IntegrationService();

        $data = [
            'marketplace' => Marketplace::Hepsiburada->value,
            'username'    => fake()->name(),
            'password'    => fake()->password(),
        ];

        $integration = $service->createIntegration($data);

        $this->assertDatabaseHas('integrations', $data);
        $this->assertInstanceOf(Marketplace::class, $integration->marketplace);
        $this->assertEquals($data['username'], $integration->username);
        $this->assertEquals($data['password'], $integration->password);
    }

    /** @test */
    public function an_integration_can_be_update_via_unit() {
        $service = new IntegrationService();

        $integration = Integration::factory()->create();

        $newData = [
            'marketplace' => Marketplace::Trendyol->value,
            'username'    => fake()->name(),
            'password'    => fake()->password(),
        ];

        $updatedIntegration = $service->updateIntegration($integration->id, $newData);
        $this->assertInstanceOf(Marketplace::class, $updatedIntegration->marketplace);
        $this->assertEquals($newData['username'], $updatedIntegration->username);
        $this->assertEquals($newData['password'], $updatedIntegration->password);
    }

    /** @test */
    public function an_integration_can_be_delete_via_unit() {
        $service = new IntegrationService();

        $integration = Integration::factory()->create();

        $this->assertDatabaseHas('integrations', ['id' => $integration->id]);

        $service->deleteIntegration($integration->id);

        $this->assertDatabaseMissing('integrations', ['id' => $integration->id]);
    }


}
